name: Daily Email Parse
on:
  schedule:
    - cron: '0 8 * * *' # Runs at 8:00 UTC (adjust for your timezone)
  workflow_dispatch: # Allows you to click "Run" manually to test

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install firebase-admin beautifulsoup4
      - name: Create Key File
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: |
          echo "$FIREBASE_KEY" > serviceAccountKey.json
      - name: Run Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python email_bot_cloud.py
